### ISSUE TITLE
[ terraform-ibm-observability-agents/modules/logs-agent] Include variables to configure agent resources

### ISSUE THREAD

**Issue by fidel-ibm** [terraform-ibm-modules/terraform-ibm-observability-agents#469]
Currently the agent doesn't expose a variable to configure the logs-agent resources, although is supported from the logs-agent helm chart

```
resources:
  limits:
    cpu: 500m
    ephemeral_storage: 10Gi
    memory: 3Gi
  requests:
    cpu: 100m
    ephemeral_storage: 2Gi
    memory: 1Gi
```
